### ISSUE TITLE
IMDb sends 403 code

### ISSUE THREAD

**Issue by luksbutz** [kenshaw/imdb#1]
Hi,
I really like your module and used it for quite some time now.
Today I discovered that IMDb is blocking my requests.
I always receive the status code 403, tried changing the user agent but that did not change anything.
The website works fine for me and I could also request from the cmd line with curl or wget without any problems.

```
--- FAIL: TestFindTitle (0.12s)
    httplog.go:105: -> GET /find?q=bob+burger&s=tt HTTP/1.1
        -> Host: www.imdb.com
        -> User-Agent: wget
        -> Accept-Encoding: gzip
        ->
        ->

    httplog.go:105: <- HTTP/2.0 403 Forbidden
        <- Content-Length: 118
        <- Alt-Svc: h3=":443"; ma=86400
        <- Content-Type: text/html
        <- Date: Thu, 22 Dec 2022 14:14:11 GMT
        <- Server: Server
        <- Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
        <- Vary: Content-Type,Accept-Encoding,User-Agent
        <- Via: 1.1 511c8b6c7e903efca023a504d527516a.cloudfront.net (CloudFront)
        <- X-Amz-Cf-Id: 8KgmjsrxeItEH6xphqZO_KQwcpfpjJdserS4UAqiVoRQWqPDgkfoJA==
        <- X-Amz-Cf-Pop: FRA53-C1
        <- X-Amz-Rid: K3YTKZKH9JVABAN1YAZA
        <- X-Cache: Error from cloudfront
        <-
        <- <html>
        <- <head><title>403 Forbidden</title></head>
        <- <body>
        <- <center><h1>403 Forbidden</h1></center>
        <- </body>
        <- </html>
        <-

    imdb_test.go:12: expected no error, got: status code 403 != 200
```

**Comment by kenshaw** [comment]
@luksbutz Amazon/IMDb have decided to block scrapers for the first time (that I'm aware of) in the last ~20 years. I had tried to keep up and fix the package, but it's not possible any more. As such, I've moved all my scripts to using `github.com/ryanbradynd05/go-tmdb`. While the package isn't as "Go idoimatic" as I'd like, it works, and that's really all that matters. I'm not planning on fixing this package to work with IMDb, but will not archive the repo in case others are able to get it to work again with IMDb.

**Comment by luksbutz** [comment]
Ok it works again. I was using it with your diskcache module and so switching the UserAgent did not work because it was already cached. After removing the cache folder and using any other Agent but "wget" everything seems to work properly.

**Comment by kenshaw** [comment]
@luksbutz if you're doing a small / minimal number of queries, it'll probably work just fine. The issue that I have with it is the limiting, which as you can imagine when I also use it with `diskcache` causes bad queries. As such, I've just decided to move on from IMDb, which has been a long time coming. Glad it works for you in general!
